[tool.poetry]
name = "saasboilerplate"
version = "0.1.0"
description = "This is the backend for the Software-as-a-Service boilerplate app"
authors = ["Lars Schellhas <lars.schellhas@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^3.1.5"
django-filter = "^2.4.0"
djangorestframework = "^3.12.2"
Markdown = "^3.3.3"
django-countries = "^7.0"
django-cors-headers = "^3.7.0"
django-username-email = "^2.4.1"
whitenoise = "^5.2.0"
psycopg2-binary = "^2.8.6"
django-extensions = "^3.1.0"
django-money = "^2.0.1"
drf-app-generators = "^0.1.5"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
autopep8 = "^1.5.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
